### ISSUE TITLE
特定の環境で Cursor の画面がちらつく

### ISSUE THREAD

**Issue by miau** [kinopeee/cursor-perfect-guide#1]
『AIエディタCursor完全ガイド』に沿って `Cursor Setup 0.41.1 - Build 2409189xe3envg5-x64.exe` をダウンロードしWindows 環境に Cursor を導入したのですが、画面がちらつく問題が見られました。

調べてみると 2024/08/16 に Cursor コミュニティで報告されている問題で、nVidia GPU ではハードウェアアクセラレーションを無効化することで問題を回避できるとのことでした。（手元で実際に無効化＆再起動し、問題が解消されることを確認しています。）
https://forum.cursor.com/t/cursor-screen-flickering-bug/7655

執筆時点では問題なかったのだと思われますし、Cursor 本体の問題なので書籍のサポート範囲を超えているとは思いますが、一部の読者は同じ問題に当たってしまいそうなので、フォローがあると良いかもしれません。

**Comment by kinopeee** [comment]
ご承知の上で Issue を付けていただいているとは思いますけど、こちらは Cursor のサポート窓口ではないので、動作の不具合については公式フォーラムにご質問いただければと思います。

その上で、私も個人的に興味があったので、手元の NVIDIA GeForce RTX™ 3060 Ti 環境で、0.41.1、0.41.2 ともに検証しましたが、画面がちらつく現象は見られませんでした（書籍の執筆中もそうした現象は見られていません）。NVIDIA GPU というだけで発生するなら、もっと大騒ぎになっておかしくないですし、他に何か再現条件があるのかもしれません（0.38 以降の Cursor は、VSCode 1.91.1 のフォークなので、当時の VSCode でも再現しているはずです：Electron のスレッドはかなり古い情報のようです）。

お知らせの公式フォーラムのスレッドを見る限り、ユーザ同士で情報が共有されているだけで、Anysphere スタッフからコメントが付いたわけではないので、現時点では原因も対策も確たる情報はない状態のように思います。

ともあれ、ここではできないことはできないと言いますし、情報の共有は幅広にできたら良いなと考えているので、気兼ねなく Issue を付けていただいて問題ありません😊

**Comment by miau** [comment]
検証まで実施いただきありがとうございます。私の環境特有の問題だったとのことで失礼しました。
nVidia GPU だと発生するようなことが書かれていたので他の読者の方も困るのではと思いご報告させていただきましたが、誰も困らなそうならよかったです。

なお、せっかく情報をいただいたので VSCode 1.91.1 も試したのですが、こちらでは問題は再現せず Cursor 特有の問題がありそうではありました。Cursor は過去バージョンが配布されておらずこれ以上検証できないのですが、もし他の読者の方に影響するような情報に当たりましたら改めてご報告させていただきます。

**Comment by kinopeee** [comment]
Electron の問題なら、同じ Electron バージョンのレンダリングエンジンを積んでいる VSCode 1.91.1 で再現しないとおかしいので、それ以外の原因、または原因の組み合わせがありそうですね。ちなみに、Cursorのバージョン番号を見ると、Electron、Chromium、Node.jsなどの情報も確認することができます。
![CleanShot 2024-09-25 at 03 01 51](https://github.com/user-attachments/assets/c96fb26e-aeae-4905-a860-2a3d3ae70839)

また何か情報がありましたら、教えてください！
