### ISSUE TITLE
getting_started.mdが日本語になっている

### ISSUE THREAD

**Issue by yamatoto** [kinopeee/cursor-perfect-guide#2]
書籍ではAIを使ってチュートリアルの文章を英語から日本語にしようというハンズオンですが、
現在の公式のcursorはダウンロードしてもCURSOR-TUTORは存在しない為、
[こちら](https://github.com/kinopeee/cursor-tutor/)のリポジトリをダウンロードしたのですが、
[getting_started.md](https://github.com/kinopeee/cursor-tutor/blob/main/getting_started.md)が日本語であるため
AIを使って英語から日本語へ変換してもらうハンズオンができません。

**Comment by kinopeee** [comment]
書籍のご購入をありがとうございます！
ご質問の件ですが、Cursorのデフォルトのインストールで cursor-tutor が付属しなくなったため、cursor-tutor リポジトリを用意しました。その際、元のファイルの内容そのままで著作権などの問題が生じてしまう可能性を避けるために、あえて日本語での手順説明とさせていただきました。そのため、[README.md](https://github.com/kinopeee/cursor-tutor/blob/main/README.md) ファイルに下記のように記載させていただきました。

> 本書内では、英語の手順説明部を訳しながら操作を進めていますが、こちらのサンプルでは最初から日本語にしてあります。

書籍と全く同じ手順を踏むことができずに申し訳ありませんが、上記の点をご理解いただければ幸いです。
英語→日本の手順はスキップしていただくか、あえて、日本語→英語を試してみるなどして、Cursor の使い方を試していただければと思います。

なお、[「AIエディタCursor完全ガイド」出版＋重版＆創業30周年記念Tシャツプレゼント・キャンペーン](https://www.key-planning.co.jp/30th_anniversary_tshirt/ ) を開始しましたので、ぜひご応募ください！
