### ISSUE TITLE
P115の4.1、チームで共有できる「Docs」機能について内容の誤記があります。

### ISSUE THREAD

**Issue by tks-00** [kinopeee/cursor-perfect-guide#4]
## 問題

書籍には

- 「チーム内で[Docs]を共有する事ができます。Onにすることで、その[docs]がチーム内で共有されます。」

と記載がありますが、Cursor サポートに問い合わせた所、下記の様に回答をいただきました。

> Currently, Cursor doesn't have a built-in document sharing feature - the "SHARE WITH TEAM" toggle you're seeing is actually for our @Docs feature, which allows you to index external documentation for AI queries within Cursor.
> 
> When you add a document URL with "SHARE WITH TEAM" enabled, it only indexes that documentation to be used as context for AI responses within your Cursor environment. It doesn't create or share documents between team members.

（日本語訳）

> 現在、Cursorにはビルトインのドキュメント共有機能はありません。あなたが見ている 「SHARE WITH TEAM 」トグルは、実は@Docs機能のためのもので、Cursor内のAIクエリのために外部ドキュメントのインデックスを作成することができます。
> 
> SHARE WITH TEAM "を有効にしてドキュメントのURLを追加すると、Cursor環境内でAIレスポンスのコンテキストとして使用されるドキュメントのインデックスのみが作成されます。チームメンバー間でドキュメントを作成したり共有したりすることはできません。

又、SHARE WITH TEAM のオンとオフの違いに関しては下記の様に回答いただいてます。

> When "SHARE WITH TEAM" is enabled, the indexed documentation becomes available as context for AI queries for all members of your team. When it's off, only you can use that documentation as context in your AI interactions.

（日本語訳）

> SHARE WITH TEAM "を有効にすると、インデックス化されたドキュメントは、チームメンバー全員のAIクエリのコンテキストとして利用できるようになります。これがオフの場合、AIとのやり取りでそのドキュメントをコンテキストとして使用できるのはあなただけです。

## まとめ

つまり下記の様な認識が正しいかと思います。

- メンバー間でドキュメント自体の共有は出来ず、ドキュメントのインデックス化されたものが共有される。

### （例）プロジェクトA仕様書.txt というドキュメントを追加した場合

- 「SHARE WITH TEAM」がオンの場合
・自分のアカウントによる AI の回答：仕様書の内容を参照して回答できる
・自分以外のメンバーのアカウントによる AI の回答：仕様書の内容を参照して回答できる
・自分のアカウント：追加したドキュメントが確認出来る。
・自分以外のメンバーのアカウント：追加したドキュメントが確認出来ない。

- 「SHARE WITH TEAM」がオフの場合
・自分のアカウントによる AI の回答：仕様書の内容を参照して回答できる
・自分以外のメンバーのアカウントによる AI の回答：　仕様書の内容を参照できないため、一般的な回答しかできない
・自分のアカウント：追加したドキュメントが確認出来る。
・自分以外のメンバーのアカウント：追加したドキュメントが確認出来ない。

**Comment by tks-00** [comment]
@kinopeee 
当初、[chapter4の所](https://github.com/kinopeee/cursor-perfect-guide/tree/main/chapter4)にPR出そうかと思ったのですが、README.mdにて4.3~4.5までは書いているが4.1に関しては特に記載がなかったので、一旦まずはissueとして投げさせていただきました。
こちらの内容で問題なければ PR を出させていただこうかと思います。

ご確認、よろしくお願いいたします。

**Comment by kinopeee** [comment]
書籍にある記載は @Docs についてのもので、ご質問のように、自作のファイルの共有ができるという説明ではありません。
チームプランの場合にDocs の設定画面に「SHARE WITH TEAM」トグルが表示されるもので、もともとの Docs にないファイルの共有ができるわけではありません。

**Comment by tks-00** [comment]
改めて読み返して確かにそうでした。
私の読解力が不足してました。

お手数おかけしてすみません！！！
（closeしていただいて問題ございません！）

**Comment by kinopeee** [comment]
いえいえ、またわからない点があったらお知らせください。
