### ISSUE TITLE
教えてもらえませんか？

### ISSUE THREAD

**Issue by MotoHoki** [kinopeee/cursor-perfect-guide#5]
完全ガイドで勉強していますが、テーブルでつまづいています。
▽１９４頁の３からできません。「Interpreter Mode]が選択できません。
７の[auto-excutte]ボタンもありません。
８、９に進めません。

▽GITのマニュアル
sql_practice.sqlite →その他のツールＣＳＶのインポートも試しましたが、
なかなかうまくいきません。

▽windows /SQlite 3.46.1です。

打開策を教えてもらえないでしょうか？

**Comment by kinopeee** [comment]
Cursor のバージョンは 0.43 をお使いですか？
0.43 ではいくつか大きな変更があって、書籍の手順通りの操作ができません。現在、サポートリポジトリも 0.43 に対応したものに書き換えているので、もう少しの間お待ちいただけますでしょうか。

**Comment by MotoHoki** [comment]
kinopeeeさま
早速の返信ありがとうございます。
バージョンは 0.43.5になっています。
リポジトリの更新、お待ちしています。

私はプログラム初心者です。
ＳＱＬも初めてなので、じっくり勉強します。

この本はとても参考になります。私の知る限り、
国内でCursorの解説本は、この本だけと思うので、
わかりやすくなるように進めてください。

将来的な希望なのですが、youtube動画で解説を
していただければ、助かります。
バージョンを調べるのにも時間がかかる初学者には
本だけでは、なかなか理解が進まないのが現状です。

cursorはとても便利だと思うので、時間をかけてでも
習得していきたいと考えています。

それでは。寒くなりますのでお体ご自愛ください。

**Comment by kinopeee** [comment]
ご理解をありがとうございます。
ちょっと残念なことに文字化けしていて読めない箇所があるので、編集しておいていただけると助かります。
読者の皆様のご意見を知っておきたいと考えていますので。

**Comment by kinopeee** [comment]
サポートリポジトリの内容が 0.43 に対応しました。
Interpreter Mode はより強化された機能として、Composer の agent モードが実装されました。Interpreter Mode を使用している場面では、Composer agent をお使いください。Composer agent については、第6章の説明をご参照ください。
